reviews:
  profile: chill
  sequence_diagrams: false
  poem: false
  high_level_summary: false
  changed_files_summary: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_reviewers: false
  in_progress_fortune: false
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
issue_enrichment:
  auto_enrich:
    enabled: false
