on:
  workflow_call: { }

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - name: Retrieve minimal supported rust version
        id: rust_version
        run: echo "value=$(sed -ne 's/rust-version *= *\"\(.*\)\"/\1/p' Cargo.toml)" >> $GITHUB_OUTPUT
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.rust_version.outputs.value }}
          target: ${{ matrix.target }}
          components: clippy, rustfmt, llvm-tools-preview
      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
