on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      rust_version: ${{ steps.rust_version.outputs.value }}
    steps:
      - name: Retrieve minimal supported rust version
        id: rust_version
        run: echo "value=$(sed -ne 's/rust-version *= *\"\(.*\)\"/\1/p' Cargo.toml)" >> $GITHUB_OUTPUT
  run:
    needs: prepare
    runs-on: ubuntu-24.04
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ needs.prepare.outputs.rust_version }}
          target: ${{ inputs.target }}
          components: clippy, rustfmt, llvm-tools-preview
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: ${{ needs.prepare.outputs.rust_version }}
      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
