name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  XDG_RUNTIME_DIR: "~"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CODECOV_UPLOAD: true

jobs:
  clippy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-2025
            target: x86_64-pc-windows-msvc
          - name: Linux
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - name: macOS
            os: macos-15
            target: x86_64-apple-darwin
    name: Clippy - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Retrieve rust version
        id: rust_version
        run: bash -x .github/scripts/extract_rust_version.sh
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.rust_version.outputs.value }}
          target: ${{ matrix.target }}
          components: clippy
      - name: Setup cache for Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-bin: false
      - name: Run clippy
        run: cargo clippy --all-targets --no-deps --target ${{ matrix.target }} -- -D warnings

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Retrieve rust version
        id: rust_version
        run: bash -x .github/scripts/extract_rust_version.sh
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.rust_version.outputs.value }}
          target: x86_64-unknown-linux-gnu
          components: llvm-tools-preview
      - name: Setup cache for Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-bin: false
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: grcov
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.335.0
          cache: true
      - name: Install Mesa
        uses: gfx-rs/wgpu/.github/actions/install-mesa@v28
      - name: Run unit tests
        run: cargo test --no-fail-fast
        env:
          RUSTFLAGS: -Cinstrument-coverage -Clink-dead-code
          LLVM_PROFILE_FILE: "%m.profraw"
      - name: Generate coverage report
        run: |
          grcov . \
              --binary-path ./target/debug/ \
              --source-dir . \
              --output-type cobertura \
              --branch \
              --ignore-not-existing \
              --output-path ./coverage.xml \
              --excl-line '(#\[|^[^ ]+!\(|struct |impl( |<)|unreachable!|^\/\/\/|no-coverage|[a-z0-9_]: .+,)' \
              --excl-start 'coverage: off' \
              --excl-stop 'coverage: on' \
              --keep-only "src/**/*"
      - name: Upload coverage report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage.xml
          if-no-files-found: error
          retention-days: 7
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libxml2-utils
      - name: Check coverage threshold
        run: bash -x .github/scripts/check_coverage.sh

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Git check
        run: git diff main --check
      - name: Retrieve rust version
        id: rust_version
        run: bash -x .github/scripts/extract_rust_version.sh
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.rust_version.outputs.value }}
          target: x86_64-unknown-linux-gnu
          components: rustfmt
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: ${{ steps.rust_version.outputs.value }}
      - name: Setup cache for Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-bin: false
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y moreutils shellcheck
      - name: Lint Bash scripts
        run: shellcheck .github/scripts/*.sh --shell bash --severity style --external-sources
      - name: Install shfmt
        run: curl -sS https://webi.sh/shfmt | sh; source ~/.config/envman/PATH.env
      - name: Check Bash script formatting
        run: shfmt --indent 4 -l .github/scripts/*.sh
      - name: Run Rust code formatting
        run: cargo fmt -- --check
      - name: Check encoding
        run: isutf8 -- **/*
      - name: Detect line endings different than '\n'
        run: bash .github/scripts/check_line_endings.sh
      - name: Detect TODOs
        run: bash .github/scripts/check_todos.sh
      - name: Check file paths
        run: bash .github/scripts/check_file_paths.sh
      - name: Check Rust identifiers
        run: bash .github/scripts/check_identifiers.sh
      - name: Detect incorrect impl block ordering
        run: bash .github/scripts/check_impl_order.sh
      - name: Detect disallowed empty lines in function bodies
        run: bash .github/scripts/check_function_body_empty_lines.sh
      - name: Detect inline mod statements that are not at the top of a file
        run: bash .github/scripts/check_mod_location.sh
      - name: Detect function called after their definition
        run: bash .github/scripts/check_function_order.sh
      - name: Generate documentation
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: -Dwarnings
